---

- name: docker | setup dnf repository
  become: true
  ansible.builtin.dnf:
    update_cache: true
    state: present
    name: dnf-plugins-core

- name: setup dnf repository
  become: true
  community.general.dnf_config_manager:
        add_repo: https://download.docker.com/linux/centos/docker-ce.repo

- name: INSTALL  docker
  ansible.builtin.dnf:
    name:
      - docker-ce
      - docker-ce-cli
      - containerd.io
    state: present
  become: yes

- name: Enable and restart a docker service
  ansible.builtin.service:
    name: docker
    state: restarted
    enabled: true



